### ISSUE TITLE
表型文件标准化

### ISSUE THREAD

**Issue by CuteGold0407** [zpliu1126/eQTL_pipeline#1]
您好~表型文件的标准化有什么软件推荐吗？原来fastqtl的--normal参数好想可以实现这个功能，但是现在tensorqtl好像没有这个参数了。看了您写的脚本，有点不太明白，不知道有什么简单一些的方法吗？谢谢！

**Comment by zpliu1126** [comment]
可以试试R里面的qqnorm函数
![image](https://github.com/zpliu1126/eQTL_pipeline/assets/39325949/a02c3ea5-e29d-4559-8d6b-8960c34aeba2)

**Comment by zpliu1126** [comment]
我脚本是基于这个函数对数据进行标准化的，你可以用pyhon跑和R跑。看看结果是不是差不多的
● 基于rank的逆正态化函数(将非正态化数据转变为正态化数据)

>参考:  https://www.biostars.org/p/80597/
```R
normal <- function(x)
{
  qnorm((rank(x, na.last = "keep") - 0.5) / sum(!is.na(x)))
}
```

**Comment by CuteGold0407** [comment]
谢谢！已经在试了！好像可以正确输出结果！
